# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mod_photo_config = debug
endif

PROJECTS := mod_photo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mod_photo:
ifneq (,$(mod_photo_config))
	@echo "==== Building mod_photo ($(mod_photo_config)) ===="
	@${MAKE} --no-print-directory -C . -f mod_photo.make config=$(mod_photo_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f mod_photo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mod_photo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"